source 'https://rubygems.org'
ruby "2.1.2"

gem 'bundler'
gem 'rack-contrib', :require => 'rack/contrib/try_static'
gem 'thin'
gem 'jekyll'
gem 'RedCloth'
gem 'rdiscount'
gem 'therubyracer'
gem 'less'
gem 'json'
gem 'closure-compiler'
#gem 'highline'
gem 'colorize'
gem 'chronic'
gem 'jekyll-sitemap'
