source 'https://rubygems.org'

gem 'rack-contrib', :require => 'rack/contrib/try_static'
#gem 'rack-redirect'
gem 'thin'

gem 'jekyll'
gem 'RedCloth'
gem 'rdiscount'
gem 'therubyracer'
gem 'less'
gem 'json'
gem 'closure-compiler'
#gem 'highline'
gem 'colorize'
